import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { LocaleSwitcher } from '../components/locale-switcher'
import { routes } from '../lib/routes'

const Home: NextPage = () => {
  const router = useRouter()
  const { locale, locales, defaultLocale } = router
  const baseRoute = routes.products[locale || defaultLocale || '']
  const categoryRoute = routes.categories[locale || defaultLocale || '']

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Localized routing</h3>

        <div className={styles.description}>
          <p>Current locale: {locale}</p>
          <p>Default locale: {defaultLocale}</p>
          <p>Configured locales: {JSON.stringify(locales)}</p>
        </div>

        <LocaleSwitcher />

        <div className={styles.grid}>
          <ul>
            <li>
              <Link href={`/${baseRoute}/${categoryRoute}`}>
                {locale === 'fr' ? 'Produits' : 'Producten'}
              </Link>
            </li>
            <li>
              {' '}
              <Link href={`/${baseRoute}/${categoryRoute}`}>
                {locale === 'fr' ? 'Page de catégorie' : 'Categorie pagina'}
              </Link>
            </li>
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
